language: nodes_js
node_js:
  - "10.15"
branches:
  only:
  - master
before_script:
  - sudo apt-get install -y findutils openssh-client sshpass
  - npm install -g @angular/cli
script:
  - cd webapp
  - npm install
  - ng build --prod
after_success:
  - echo "uploading to $FTP_SERVER"
  - cd ..
  - cp server/data.php webapp/dist/webapp/
  - cd webapp/dist/webapp/
  - $SSH_FINGERPRINT >> ~/.ssh/known_hosts
  - sshpass -p "$FTP_PASSWORD" scp -vrC * $FTP_USER@$FTP_SERVER:/
