language: nodes_js
node_js:
  - "10.15"
branches:
  only:
  - master
before_script:
  - sudo apt-get install -y sshpass
  - npm install -g @angular/cli
script:
  - cd webapp
  - npm install
  - ng build --prod
deploy:
  provider: gae
  keyfile: "YOUR SERVICE ACCOUNT JSON FILE"
  project: "$GAE_PROJECT_ID"
