language: nodes_js
node_js:
  - "10.15"
branches:
  only:
  - master
before_script:
  - npm install -g @angular/cli
script:
  - cd webapp
  - npm install
  - ng build --prod
  - ls -l dist
after_success:
  - echo "uploading to $FTP_SERVER"
  - curl --verbose -ftp-create-dirs -T server/data.php ftp://$FTP_USER:$FTP_PASSWORD@$FTP_SERVER
