language: nodes_js
node_js:
  - "10.15"
branches:
  only:
  - master
before_script:
  - sudo apt-get install -y findutils
  - npm install -g @angular/cli
script:
  - cd webapp
  - npm install
  - ng build --prod
after_success:
  - echo "uploading to $FTP_SERVER"
  - cd ..
  - FILES="server/data.php"
  - find webapp/dist/webapp -type f -exec FILES="$FILES,{}" \;
  - echo $FILES
  - curl --verbose -ftp-create-dirs -T "{$FILES}" ftp://$FTP_USER:$FTP_PASSWORD@$FTP_SERVER
