language: nodes_js
node_js:
  - "10.15"
branches:
  only:
  - master
before_script:
  - sudo apt-get install -y findutils
  - npm install -g @angular/cli
script:
  - cd webapp
  - npm install
  - ng build --prod
after_success:
  - echo "uploading to $FTP_SERVER"
  - cd ..
  - FILES=`ls webapp/dist/webapp | tr "\n" "," | head -c -1 | sed -e 's/,/,webapp\/dist\/webapp\//g'`
  - FILES="server/data.php,webapp/dist/webapp/"$FILES
  - echo $FILES
  - curl --verbose -ftp-create-dirs --disable-epsv -T "{$FILES}" ftp://$FTP_USER:$FTP_PASSWORD@$FTP_SERVER/
